### ISSUE TITLE
Failed to export an ONNX attribute 'onnx::Gather'

### ISSUE THREAD

**Issue by tucachmo2202** [codylcs/files#1]
Thank for your guide,
But when I try convert lite_hrnet with your code with model Lite-HRNet-18, it raise the error:
RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible
`RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible
`
could you please fix it for me? Thank you very much!

**Comment by codylcs** [comment]
> Thank for your guide,
> But when I try convert lite_hrnet with your code with model Lite-HRNet-18, it raise the error:
> RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible
> `RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible `
> could you please fix it for me? Thank you very much!

u should chane directly replace the "adaptive_avg_pool2d" with the normal average pooling with a definite pooling size.
Then, it can be converted to onnx format. question [here](https://github.com/HRNet/Lite-HRNet/issues/3)

this change i just have not upload to this rep

**Comment by tucachmo2202** [comment]
@codylcs thanks for your reply, but I don't know how to change T..T. Could you please give me the lite_hrnet.py file? S2

**Comment by codylcs** [comment]
> @codylcs thanks for your reply, but I don't know how to change T..T. Could you please give me the lite_hrnet.py file? S2

yes, i will upload lite_hrnet.py

**Comment by codylcs** [comment]
> @codylcs thanks for your reply, but I don't know how to change T..T. Could you please give me the lite_hrnet.py file? S2

i just have uploaded [litehrnet.py](https://github.com/codylcs/lite_hrnet_onnx/blob/main/litehrnet.py),u can try now

**Comment by tucachmo2202** [comment]
> i just have uploaded [litehrnet.py](https://github.com/codylcs/lite_hrnet_onnx/blob/main/litehrnet.py),u can try now

It worked perfectly. Thanks a lot!
